package database

import (
	"fmt"
	"os"
	"strings"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

type Config struct {
	Host     string
	Port     string
	User     string
	Password string
	Name     string
	SSLMode  string
}

func ConfigFromEnv() Config {
	return Config{
		Host:     env("DB_HOST", "127.0.0.1"),
		Port:     env("DB_PORT", "5432"),
		User:     env("DB_USER", "player"),
		Password: env("DB_PASSWORD", "p"),
		Name:     env("DB_NAME", "player"),
		SSLMode:  env("DB_SSLMODE", "disable"),
	}
}

func Open(cfg Config) (*gorm.DB, error) {
	dsn := fmt.Sprintf(
		"host=%s port=%s user=%s password=%s dbname=%s sslmode=%s",
		cfg.Host,
		cfg.Port,
		cfg.User,
		cfg.Password,
		cfg.Name,
		cfg.SSLMode,
	)

	return gorm.Open(postgres.Open(dsn), &gorm.Config{})
}

func Migrate(db *gorm.DB) error {
	statements := []string{
		`CREATE TYPE "PlayerStatus" AS ENUM ('ACTIVE', 'BANNED', 'DELETED')`,
		`CREATE TYPE "PlayerClass" AS ENUM ('WARRIOR', 'MAGE', 'ROGUE', 'PRIEST', 'HUNTER')`,
		`CREATE TABLE IF NOT EXISTS guild (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			name text NOT NULL UNIQUE,
			description text,
			"foundedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
			version integer NOT NULL DEFAULT 0
		)`,
		`CREATE TABLE IF NOT EXISTS player (
			id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			username text NOT NULL UNIQUE,
			email text NOT NULL UNIQUE,
			level integer NOT NULL DEFAULT 1,
			experience integer NOT NULL DEFAULT 0,
			"playerClass" "PlayerClass" NOT NULL,
			status "PlayerStatus" NOT NULL DEFAULT 'ACTIVE',
			"guildId" integer REFERENCES guild(id) ON DELETE SET NULL ON UPDATE CASCADE,
			"createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
			"updatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
			version integer NOT NULL DEFAULT 0
		)`,
		`CREATE INDEX IF NOT EXISTS player_guild_id_idx ON player("guildId")`,
	}

	for _, statement := range statements {
		if err := db.Exec(statement).Error; err != nil && !isDuplicateObject(err) {
			return err
		}
	}
	return nil
}

func isDuplicateObject(err error) bool {
	return err != nil && (strings.Contains(err.Error(), "SQLSTATE 42710") || strings.Contains(err.Error(), "already exists"))
}

func env(key string, fallback string) string {
	value := os.Getenv(key)
	if value == "" {
		return fallback
	}
	return value
}
