services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: tmp
      KC_BOOTSTRAP_ADMIN_PASSWORD: p
    ports:
      - "8880:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import:ro

volumes:
  keycloak-data:
