-- Bestehende Tabellen und Typen löschen (nur für Entwicklung/Neuaufbau!)

SET search_path TO public;

DROP TABLE IF EXISTS player CASCADE;
DROP TABLE IF EXISTS guild CASCADE;
DROP TYPE IF EXISTS "PlayerStatus" CASCADE;
DROP TYPE IF EXISTS "PlayerClass" CASCADE;

-- Aufruf: psql --dbname=player --username=player --file=/init/player/sql/create-table.sql

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'PlayerStatus'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "PlayerStatus" AS ENUM ('ACTIVE', 'BANNED', 'DELETED');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'PlayerClass'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE "PlayerClass" AS ENUM ('WARRIOR', 'MAGE', 'ROGUE', 'PRIEST', 'HUNTER');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS guild (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text,
  "foundedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version integer NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS player (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  level integer NOT NULL DEFAULT 1,
  experience integer NOT NULL DEFAULT 0,
  "playerClass" "PlayerClass" NOT NULL,
  status "PlayerStatus" NOT NULL DEFAULT 'ACTIVE',
  "guildId" integer REFERENCES guild(id) ON DELETE SET NULL ON UPDATE CASCADE,
  "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS player_guild_id_idx ON player("guildId");
