' Copyright (C) 2026 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml ER Diagramm Player

hide circle
skinparam linetype ortho

entity "Player" {
  * id: integer <<generated>>
  * username: text <<unique>>
  * email: text <<unique>>
  * level: integer
  * experience: integer
  * playerClass: text
  * status: text
  * guildId: integer <<FK>>
  * createdAt: timestamp
  * updatedAt: timestamp
  * version: integer
}

entity "Guild" {
  * id: integer <<generated>>
  * name: text <<unique>>
    description: text
  * foundedAt: timestamp
  * version: integer
}

Player }o--|| Guild : "gehört zu"

footer (c) Jürgen Zimmermann

@enduml
