' Copyright (C) 2026 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Player-Write-Router

interface Promise<T>

package hono.context {
  class Context<E, P, I>
  interface JSONRespondReturn<T, U> <<type>>

  Context .down[hidden].> JSONRespondReturn
}

package generated.prisma {
  class Prisma
  note left: + bedeutet innere Klasse

  class PlayerCreateInput
  class PlayerUpdateInput
  Prisma +-- PlayerCreateInput
  Prisma +-- PlayerUpdateInput
}

package player {
  package service {
    class PlayerWriteService << control >>
  }

  package router #DDDDDD {
    object "post('/', async handler): JSONRespondReturn" as post <<function>>
    object "put('/:id', async handler): JSONRespondReturn" as put <<function>>
    object "delete('/:id', async handler): JSONRespondReturn" as delete <<function>>

    post .down[hidden].> put
    put .down[hidden].> delete

    post .right[hidden].> PlayerWriteService
    delete .right[hidden].> PlayerWriteService
    delete .down[hidden].> Prisma

    post .up.> Promise
    post .right.> Context
    post .right.> JSONRespondReturn
    post .right.> PlayerWriteService
    post .down.> PlayerCreateInput

    put .up.> Promise
    put .right.> Context
    put .right.> JSONRespondReturn
    put .right.> PlayerWriteService
    put .down.> PlayerUpdateInput

    delete .up.> Promise
    delete .right.> Context
    delete .right.> JSONRespondReturn
    delete .right.> PlayerWriteService
  }
}

hide empty members

footer (c) Juergen Zimmermann

@enduml
