' Copyright (C) 2026 - present Juergen Zimmermann, Hochschule Karlsruhe
'
' This program is free software: you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation, either version 3 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program.  If not, see <https://www.gnu.org/licenses/>.

' Preview durch <Alt>d

@startuml Sequenzdiagramm Player

actor Gast

boundary "Hono App" as hono
control "router\n(in player-router)" as playerRouter
control PlayerService
control PrismaClient

group GET /rest/player/:id
  Gast -> hono: GET /rest/player/1
  hono -> playerRouter: router.get('/:id')
  playerRouter -> PlayerService: findById(id)
  PlayerService -> PrismaClient: player.findUnique({ id })
end

footer (c) Jürgen Zimmermann

@enduml
